### ISSUE TITLE
Godot Rougelike Tutorial (Episode 7)

### ISSUE THREAD

**Issue by DevLMMK** [MateuSai/Godot-Roguelike-Tutorial#3]
Hey dude! I've been following your Godot tutorials, which are amazing and exactly what I've been looking for. Now I'm stuck on your seventh video. To put it simply: the entrance will not close. I did exactly what you did with the Tile Maps 1 & 2 with the 2 single tile and one atlas tile. Before I gave up, I tried one thing. I printed in the  _close_entrance() function... And it worked. So, I'm confused why the entrance won't close. Everything rather than that works. Thanks.

Room0:
extends Node2D

const SPAWN_EXPLOSION_SCENE: PackedScene = preload("res://CHARACTERS/ENEMIES/Spawn_Explosion.tscn")
const ENEMY_SCENES: Dictionary = {
	"FLYING_ENEMY": preload("res://CHARACTERS/ENEMIES/FLYING_ENEMY/Flying_Enemy.tscn")
}

var num_enemy: int

onready var tile_map: TileMap = get_node("Navigation2D/TileMap2")
onready var entrance: Node2D = get_node("Entrance")
onready var door_container: Node2D = get_node("Doors")
onready var enemy_positions_box: Node2D = get_node("Enemy_Positions")
onready var player_detection: Area2D = get_node("Player_Detection")

func _ready() -> void:
	num_enemy = enemy_positions_box.get_child_count()

func _on_enemy_killed() -> void:
	num_enemy -= 1
	if num_enemy == 0:
		_open_doors()

func _open_doors() -> void:
	for door in door_container.get_children():
		door.open()

func _close_entrance() -> void:
	for entry_position in entrance.get_children():
		tile_map.set_cellv(tile_map.map_to_world(entry_position.global_position), 1)
		tile_map.set_cellv(tile_map.map_to_world(entry_position.global_position) + Vector2.DOWN, 2)
		print("sans")

func _spawn_enemies() -> void:
	for enemy_positions in enemy_positions_box.get_children():
		var enemy: KinematicBody2D = ENEMY_SCENES.FLYING_ENEMY.instance()
		var __ = enemy.connect("tree_exited", self, "_on_enemy_killed")
		enemy.global_position = enemy_positions.global_position
		call_deferred("add_child", enemy)
		
		var spawn_explosion: AnimatedSprite = SPAWN_EXPLOSION_SCENE.instance()
		spawn_explosion.global_position = enemy_positions.global_position
		call_deferred("add_child", spawn_explosion)

func _on_Player_Detection_body_entered(body: KinematicBody2D) -> void:
	player_detection.queue_free()
	_close_entrance()
	_spawn_enemies()

**Comment by MateuSai** [comment]
Hi! I think the problem is that you are using global_position to get the position of the entry Position2D. This would work if the tilemap where at the origin, but that's not the case. set_cellv expects the local coordinate of the tile, that's why we have to use position instead of global_position.

Let me explain further. The tile at the coordinate 0,0 is always at the position of the tilemap. For example, if you have the tilemap at 80,50, the tile at the coordinate 0,0 will start at 80,50, the tile at the coordinate 1,0 will start at 96,50 (considering the tiles are of 16x16). So, in this case we want the coordinate where the entry point is relative to the tilemap.

**Comment by DevLMMK** [comment]
So how do I solve this problem? What do I need to change in the script?
(and thanks for responding)

**Comment by MateuSai** [comment]
You need to take the local positions of the entry points instead of the global ones. Use `position` instead of `global_position`:

tile_map.set_cellv(tile_map.map_to_world(entry_position.**position**), 1)
tile_map.set_cellv(tile_map.map_to_world(entry_position.**position**) + Vector2.DOWN, 2)

**Comment by DevLMMK** [comment]
Thanks! I just tried that - and the walls dont show up. Sorry, I still need some help...

**Comment by MateuSai** [comment]
Hmmm, the print you mentioned, did you put it outside the for loop or inside the loop? Could it be the for loop does 0 iterations? If that's the case, check you have the Position2D nodes as children of the entrance node.

Another problem could be the position of the tilemap or the entrance node, do you have the tilemap and entrance node at the position 0,0 of their scene?

If this still does not fix the problem, share the project and I will take a look :)

**Comment by DevLMMK** [comment]
Yeah, it's inside. The position 0,0... How do I share my project with you?

**Comment by MateuSai** [comment]
You can compress the project and attach it to your message. Another option is to create a public repository with the project

**Comment by DevLMMK** [comment]
http://localhost:8060/tmp_js_export.html here it is so far
![Screen Shot 2023-06-07 at 10 23 40 AM](https://github.com/MateuSai/Godot-Roguelike-Tutorial/assets/135738873/bbb88679-9d91-4d80-893e-58c416ad1d89)
here is my Room0 
and i already showed my code
(sorry idk how to set up a repo)

**Comment by MateuSai** [comment]
I can't see anything wrong. Even if you don't create a repo, you should be able to upload the project in a message after you compress it. I don't know how it's done on mac, but normally you right click the folder and then click compress or something like that. Then drag and drop the folder to your message

**Comment by DevLMMK** [comment]
[Rougelike.zip](https://github.com/MateuSai/Godot-Roguelike-Tutorial/files/11680904/Rougelike.zip)

**Comment by MateuSai** [comment]
I found the problem, you are using map_to_world instead of world_to_map. map_to_world is used when you want to pass a tile coordinate to pixel coordinates and world_to_map is used when you want to pass a pixel coordinate to tile coordinate. In this case we want to convert the pixel coordinates of the entrance point to tile coordinates, so we must use world_to_map. I should have noticed earlier.

Also, the id of the wall, the wall that fills all the tile, is 1 and the if of the upper wall is 2. You want to put the upper wall on top and the wall that fills a tile below, so, you have to change the tile on top to id 2 and the tile below to id 1:

```
tile_map.set_cellv(tile_map.world_to_map(entry_position.position), 2)
tile_map.set_cellv(tile_map.world_to_map(entry_position.position) + Vector2.DOWN, 1)
```

**Comment by DevLMMK** [comment]
Yo man! Thank you so much! That little mistake huh? Thanks for spending your time to help me!
