### ISSUE TITLE
General Issues

### ISSUE THREAD

**Issue by DevLMMK** [MateuSai/Godot-Roguelike-Tutorial#4]
Hi again... Sorry to bother. Your tutorials are amazing. I got a few issues in this rougelike. I probably did something wrong but I don't know what it is.
1. Two of my rooms and hallways don't line up (how big or small should the rooms be?)
2. The goblins kill themselves sometimes (does this depend on the size of the room?)
3. I'm having trouble the the copy and pasting animation in Part 12. When I paste the animation the sword and slash rotate the wrong way and the slash does not go away.
[Rougelike 2.zip](https://github.com/MateuSai/Godot-Roguelike-Tutorial/files/11773311/Rougelike.2.zip)

*I subscribed ;]

**Comment by MateuSai** [comment]
Hi :).

1. On Room4, you have the Position2D of the entry inverted. The first child is at the right and the second at the left. We use these nodes to align the rooms, so they have to follow the same order on all rooms: first the position on the left and then the position on the right.

About the vertical alignment, sometimes there is a row of tiles missing. That's because we are taking the position of the door to make the corridors and it is just at the border between one tile and another, so a single pixel offset causes the tile where the door is to change. You have 2 options, move the door one pixel down so the light aligns with the adjacent tiles 

![image](https://github.com/MateuSai/Godot-Roguelike-Tutorial/assets/57108338/677b98a1-a825-4914-ac29-4076211752c6)
![image](https://github.com/MateuSai/Godot-Roguelike-Tutorial/assets/57108338/99f3299b-1861-41c0-ad28-66aebf5a0349)

By the way, the door has some weird transform, I don't know if it's intended:
![image](https://github.com/MateuSai/Godot-Roguelike-Tutorial/assets/57108338/11764689-2324-47bf-bd26-d717ab2de542)


or, if you want to leave the door where it is, change

`var exit_tile_position: Vector2 = prev_room_tilemap.world_to_map(prev_room_door.position) + Vector2.UP * 2`

to

var exit_tile_position: Vector2 = prev_room_tilemap.world_to_map(prev_room_door.position + **Vector2(8, 8))** + Vector2.UP * 2

to make sure you pick the correct tile. In that case, you may also have to change this line

`room.global_position = prev_room_door.global_position + Vector2.UP * room_tilemap.get_used_rect().size.y * TILE_SIZE + Vector2.UP * (1 + cor_height) * TILE_SIZE + Vector2.LEFT * room_tilemap.world_to_map(room.get_node("Entrance/Position2D2").global_position).x * TILE_SIZE`

to

room.global_position = **((prev_room_door.global_position + Vector2(8, 8)) / 16) * 16** + Vector2.UP * room_tilemap.get_used_rect().size.y * TILE_SIZE + Vector2.UP * (1 + cor_height) * TILE_SIZE + Vector2.LEFT * room_tilemap.world_to_map(room.get_node("Entrance/Position2D2").global_position).x * TILE_SIZE

to align the rooms correctly


2. About the goblin killing itself, the system I implemented is very stupid and may not work if the projectile goes to fast. Instead of enabling the collisions when the knife exits the goblin, now I think it's much much better to create an array called exclude or something like that. The knife has all the collisions enabled from the start and if it collides with something that is on the exclude array, it ignores it. You only have to add the goblin that throws the knife to the exclude array of the knifes he throws. You can do that on the launch function, pass a reference to the goblin and add it to the array. Then, on the _collide function you could do:

```
if exclude.has(body):
    return
```

So in case the body the knife collided with is on exclude, it will ignore it.


3. You mean the attack animation? I couldn't find a scene with sword, only the sword directly on the player scene and there the attack animation seems to work fine. The RESET animation executes automatically when the game starts, so make sure there's nothing weird there

**Comment by DevLMMK** [comment]
Alright thanks! I'ma go check out what you said now.
And if you have time - could you make a dash/dodge mechanic, chests, and maybe a bullet hell boss? 
Thanks again lol

**Comment by DevLMMK** [comment]
Sorry again. About question 2. How do I reference the goblin? Get_node() or preload() is not working for me.
And my sword attack animations don't even have a RESET.

**Comment by MateuSai** [comment]
Thanks for the suggestions, I take note :)

When you call projectile.launch(...) on the goblin script, you can pass the goblin. To get a reference of the goblin instance in the goblin script, you have to use `self`. So you can add a new parameter to `launch` and pass `self`.

In the project you uploaded, there is a RESET animation on the player sword:

![image](https://github.com/MateuSai/Godot-Roguelike-Tutorial/assets/57108338/b8a2be42-5f81-4c2d-8b07-fd2b767a9c2c)

On the RESET animation you are changing the slash sprite to visible, but it seems the cancel attack animation makes it invisible again, so that's not the problem. I don't fully understand what do you mean, you mention you pasted the animations, but where? In the video I paste the animations from the SwordAnimationPlayer to the animation player on the new scene for the sword, but you don't seem to have a scene for the sword.

**Comment by DevLMMK** [comment]
I got the weapons to work. I what is `self` though?
`func launch(initial_position: Vector2, dir: Vector2, speed: int, insert: self) -> void:`
Doesn't seem to work.

**Comment by MateuSai** [comment]
self is not a type, it is a property. self refers to the object you are in. It's what we use to connect signals by code `connect("pressed", self, "_on_pressed")`. self refers to the object from whose you are calling connect.

So, when you use self inside the goblin script, self contains the goblin object. `launch(..., self)`. Then in the function `func launch(..., insert: KinematicBody2D)`, since the goblin is of type KinematicBody2D.

Maybe this answer will help: https://ask.godotengine.org/106379/what-is-self-in-gdscript

**Comment by DevLMMK** [comment]
Where do I put `self`? I have no idea where it goes.
When I edit the sword animation is also edits the hammer one. Do you know why?

**Comment by MateuSai** [comment]
When you call launch(...) from the goblin script to launch the knife pass `self`. You are passing a reference to the goblin. You put this reference inside an array. Before inflicting damage, check if the body the hitbox collided with is inside the array. If it is, don't damage it.

About the animations, they must be sharing the same resource. I now think it would be better to delete the animations from Weapon.tscn and create them for each weapon scene, so they don't depend on the animations of the parent scene. You can also mark the animations as local to scene, if I remember correctly you click the animation button (the same you use to create new animations) and click 'open on inspector' or something like that. Then, at the inspector tab you should see a checkbox to mark the resource as local to scene

**Comment by DevLMMK** [comment]
Thanks! I got the animations to work. However for the goblins... 
Could you just give me the code? I'm still new to GDScript.
[Rougelike 3.zip](https://github.com/MateuSai/Godot-Roguelike-Tutorial/files/11818655/Rougelike.3.zip)
This is to help.

**Comment by MateuSai** [comment]
I can't do it for you, you would learn nothing. You have to try it yourself, get errors, understand them, and improve you ability. What I can do is give you an example of how I did it on Erebus. This is the function I made in Projectile.gd:

```
func launch(exclude: Array, initial_position: Vector2, dir: Vector2, speed: int, dam: int, critical_dam: int, max_time_in_air: float, weap_id_name: String, who_the_fuck_shoot_this_shit: Character, falloff: float, piercing: int = 0) -> void:
	self.exclude = exclude
```

And this is how I call the function after creating the projectile:

```
bolt.launch([character, character.hurtbox], gun_barrel.global_position, Vector2.RIGHT.rotated(deg2rad(rotation_degrees + offset + rand_dispersion)), bullet_velocity, get_damage(), _get_critical_damage(), bullet_reach, id_name, character, fallof, piercing)
```

See how I pass the character body and his hurtbox in an array, these are the collisions I want the projectile to ignore. You can check if a body is on the exclude array using `body in exclude`

**Comment by DevLMMK** [comment]
Alright... I understand now.

**Comment by DevLMMK** [comment]
Hey can you take a look at why my boss fight doesn't work?
[Rougelike 4.zip](https://github.com/MateuSai/Godot-Roguelike-Tutorial/files/11908790/Rougelike.4.zip)

**Comment by MateuSai** [comment]
I found at least 2 problems. The game crashes when you kill the slime. That's because you are trying to set the `velocity` property of the slimes you spawn, but they don't have that property, the property they have is `VELOCITY`.

Also, it seems the slime pathfinding is only updated after you hit him. That's because you are looping the jump animation, so it never ends and the slime only exits it when it's hit. Remove the loop from the jump animation

**Comment by DevLMMK** [comment]
Thanks! I fixed the boss fight for the most part.
I'm having trouble with the active ability. Can you take a look?
[Rougelike 5.zip](https://github.com/MateuSai/Godot-Roguelike-Tutorial/files/11939626/Rougelike.5.zip)

**Comment by MateuSai** [comment]
You have a typo on the line 29 of Weapon.gd on this part `anim_player.has_animation("active_abilitly")`. It sould be **"active_ability"**.

**Comment by DevLMMK** [comment]
Bro thank you so much. I would have never seen that.
I'ma triple check my code next time.

**Comment by DevLMMK** [comment]
[Rougelike.zip](https://github.com/MateuSai/Godot-Roguelike-Tutorial/files/11961741/Rougelike.zip)
Hey can you check why `initialize` doesn't exsit?

**Comment by MateuSai** [comment]
Hi, you have another type, when you call the function, you use "initialize": `new_inventory_item.initialize(weapon_texture)`. But in the declaration of the function, you use "initalize"

```
func initalize(texture: Texture) -> void:
	self.texture = texture
```

**Comment by DevLMMK** [comment]
Thanks! Sorry for responding late.
Can you check this out? The `hide` function doesn't work.
[Rougelike 2.zip](https://github.com/MateuSai/Godot-Roguelike-Tutorial/files/12009373/Rougelike.2.zip)

**Comment by MateuSai** [comment]
At what `hide` are you referring? Can you be more specific?

**Comment by DevLMMK** [comment]
`func hide() -> void:
	ability_icon.hide()
	.hide()`

**Comment by MateuSai** [comment]
If I pick the crossbow and switch between it and the sword, the ability icon is changing, so in that case `hide` is working. What I found is that the ability icon of the crossbow does not show when you first pick it up (but it shows when I switch back to it). You can fix this by calling show when the player picks the weapon:

```
func _on_Player_Detection_body_entered(body: KinematicBody2D) -> void:
	if body != null:
		player_detection.set_collision_mask_bit(0, false)
		player_detection.set_collision_mask_bit(1, false)
		body.equip_weapon(self)
		position = Vector2.ZERO
                show()
	else:
		var __ = tween.stop_all()
		assert(__)
		player_detection.set_collision_mask_bit(1, true) 
```

Where is the `hide` function not working?

**Comment by DevLMMK** [comment]
At line 93 of the Weapon Script

**Comment by MateuSai** [comment]
You have a typo at the for loop in the _restore_prev_scene function. Intead of weapons = weapon.duplicate(), it should be weapon = weapon.duplicate()

Also, it seems the first weapon is not hidden when you change scene and you have another weapon equipped. That can be fixed by hiding the first weapon before the for loop: `weapons.get_child(0).hide()`

**Comment by DevLMMK** [comment]
Thanks dude! I would have never found that.
